// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConnRoomSig.proto
package auth;

public final class ConnRoomSig {
    private ConnRoomSig() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface Conn_Room_SigOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Conn_Room_Sig)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <pre>
         * source group num
         * </pre>
         *
         * <code>uint32 uint32_groupcode = 1;</code>
         */
        int getUint32Groupcode();

        /**
         * <pre>
         * source account id
         * </pre>
         *
         * <code>string str_third_account = 2;</code>
         */
        java.lang.String getStrThirdAccount();

        /**
         * <pre>
         * source account id
         * </pre>
         *
         * <code>string str_third_account = 2;</code>
         */
        com.google.protobuf.ByteString
        getStrThirdAccountBytes();

        /**
         * <pre>
         * dest group num
         * </pre>
         *
         * <code>uint32 uint32_conned_groupcode = 3;</code>
         */
        int getUint32ConnedGroupcode();

        /**
         * <pre>
         * dest account id
         * </pre>
         *
         * <code>string str_conned_third_account = 4;</code>
         */
        java.lang.String getStrConnedThirdAccount();

        /**
         * <pre>
         * dest account id
         * </pre>
         *
         * <code>string str_conned_third_account = 4;</code>
         */
        com.google.protobuf.ByteString
        getStrConnedThirdAccountBytes();

        /**
         * <pre>
         * create time
         * </pre>
         *
         * <code>uint32 uint32_create_time = 5;</code>
         */
        int getUint32CreateTime();

        /**
         * <pre>
         * expire time
         * </pre>
         *
         * <code>uint32 uint32_expire_time = 6;</code>
         */
        int getUint32ExpireTime();
    }

    /**
     * Protobuf type {@code Conn_Room_Sig}
     */
    public static final class Conn_Room_Sig extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:Conn_Room_Sig)
            Conn_Room_SigOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use Conn_Room_Sig.newBuilder() to construct.
        private Conn_Room_Sig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private Conn_Room_Sig() {
            strThirdAccount_ = "";
            strConnedThirdAccount_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Conn_Room_Sig(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {

                            uint32Groupcode_ = input.readUInt32();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            strThirdAccount_ = s;
                            break;
                        }
                        case 24: {

                            uint32ConnedGroupcode_ = input.readUInt32();
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            strConnedThirdAccount_ = s;
                            break;
                        }
                        case 40: {

                            uint32CreateTime_ = input.readUInt32();
                            break;
                        }
                        case 48: {

                            uint32ExpireTime_ = input.readUInt32();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ConnRoomSig.internal_static_Conn_Room_Sig_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ConnRoomSig.internal_static_Conn_Room_Sig_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ConnRoomSig.Conn_Room_Sig.class, ConnRoomSig.Conn_Room_Sig.Builder.class);
        }

        public static final int UINT32_GROUPCODE_FIELD_NUMBER = 1;
        private int uint32Groupcode_;

        /**
         * <pre>
         * source group num
         * </pre>
         *
         * <code>uint32 uint32_groupcode = 1;</code>
         */
        public int getUint32Groupcode() {
            return uint32Groupcode_;
        }

        public static final int STR_THIRD_ACCOUNT_FIELD_NUMBER = 2;
        private volatile java.lang.Object strThirdAccount_;

        /**
         * <pre>
         * source account id
         * </pre>
         *
         * <code>string str_third_account = 2;</code>
         */
        public java.lang.String getStrThirdAccount() {
            java.lang.Object ref = strThirdAccount_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                strThirdAccount_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * source account id
         * </pre>
         *
         * <code>string str_third_account = 2;</code>
         */
        public com.google.protobuf.ByteString
        getStrThirdAccountBytes() {
            java.lang.Object ref = strThirdAccount_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                strThirdAccount_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int UINT32_CONNED_GROUPCODE_FIELD_NUMBER = 3;
        private int uint32ConnedGroupcode_;

        /**
         * <pre>
         * dest group num
         * </pre>
         *
         * <code>uint32 uint32_conned_groupcode = 3;</code>
         */
        public int getUint32ConnedGroupcode() {
            return uint32ConnedGroupcode_;
        }

        public static final int STR_CONNED_THIRD_ACCOUNT_FIELD_NUMBER = 4;
        private volatile java.lang.Object strConnedThirdAccount_;

        /**
         * <pre>
         * dest account id
         * </pre>
         *
         * <code>string str_conned_third_account = 4;</code>
         */
        public java.lang.String getStrConnedThirdAccount() {
            java.lang.Object ref = strConnedThirdAccount_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                strConnedThirdAccount_ = s;
                return s;
            }
        }

        /**
         * <pre>
         * dest account id
         * </pre>
         *
         * <code>string str_conned_third_account = 4;</code>
         */
        public com.google.protobuf.ByteString
        getStrConnedThirdAccountBytes() {
            java.lang.Object ref = strConnedThirdAccount_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                strConnedThirdAccount_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int UINT32_CREATE_TIME_FIELD_NUMBER = 5;
        private int uint32CreateTime_;

        /**
         * <pre>
         * create time
         * </pre>
         *
         * <code>uint32 uint32_create_time = 5;</code>
         */
        public int getUint32CreateTime() {
            return uint32CreateTime_;
        }

        public static final int UINT32_EXPIRE_TIME_FIELD_NUMBER = 6;
        private int uint32ExpireTime_;

        /**
         * <pre>
         * expire time
         * </pre>
         *
         * <code>uint32 uint32_expire_time = 6;</code>
         */
        public int getUint32ExpireTime() {
            return uint32ExpireTime_;
        }

        private byte memoizedIsInitialized = -1;

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (uint32Groupcode_ != 0) {
                output.writeUInt32(1, uint32Groupcode_);
            }
            if (!getStrThirdAccountBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, strThirdAccount_);
            }
            if (uint32ConnedGroupcode_ != 0) {
                output.writeUInt32(3, uint32ConnedGroupcode_);
            }
            if (!getStrConnedThirdAccountBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, strConnedThirdAccount_);
            }
            if (uint32CreateTime_ != 0) {
                output.writeUInt32(5, uint32CreateTime_);
            }
            if (uint32ExpireTime_ != 0) {
                output.writeUInt32(6, uint32ExpireTime_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (uint32Groupcode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, uint32Groupcode_);
            }
            if (!getStrThirdAccountBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, strThirdAccount_);
            }
            if (uint32ConnedGroupcode_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(3, uint32ConnedGroupcode_);
            }
            if (!getStrConnedThirdAccountBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, strConnedThirdAccount_);
            }
            if (uint32CreateTime_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(5, uint32CreateTime_);
            }
            if (uint32ExpireTime_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(6, uint32ExpireTime_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ConnRoomSig.Conn_Room_Sig)) {
                return super.equals(obj);
            }
            ConnRoomSig.Conn_Room_Sig other = (ConnRoomSig.Conn_Room_Sig) obj;

            if (getUint32Groupcode()
                    != other.getUint32Groupcode()) return false;
            if (!getStrThirdAccount()
                    .equals(other.getStrThirdAccount())) return false;
            if (getUint32ConnedGroupcode()
                    != other.getUint32ConnedGroupcode()) return false;
            if (!getStrConnedThirdAccount()
                    .equals(other.getStrConnedThirdAccount())) return false;
            if (getUint32CreateTime()
                    != other.getUint32CreateTime()) return false;
            if (getUint32ExpireTime()
                    != other.getUint32ExpireTime()) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + UINT32_GROUPCODE_FIELD_NUMBER;
            hash = (53 * hash) + getUint32Groupcode();
            hash = (37 * hash) + STR_THIRD_ACCOUNT_FIELD_NUMBER;
            hash = (53 * hash) + getStrThirdAccount().hashCode();
            hash = (37 * hash) + UINT32_CONNED_GROUPCODE_FIELD_NUMBER;
            hash = (53 * hash) + getUint32ConnedGroupcode();
            hash = (37 * hash) + STR_CONNED_THIRD_ACCOUNT_FIELD_NUMBER;
            hash = (53 * hash) + getStrConnedThirdAccount().hashCode();
            hash = (37 * hash) + UINT32_CREATE_TIME_FIELD_NUMBER;
            hash = (53 * hash) + getUint32CreateTime();
            hash = (37 * hash) + UINT32_EXPIRE_TIME_FIELD_NUMBER;
            hash = (53 * hash) + getUint32ExpireTime();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static ConnRoomSig.Conn_Room_Sig parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ConnRoomSig.Conn_Room_Sig parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ConnRoomSig.Conn_Room_Sig parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ConnRoomSig.Conn_Room_Sig parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ConnRoomSig.Conn_Room_Sig parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ConnRoomSig.Conn_Room_Sig parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ConnRoomSig.Conn_Room_Sig parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ConnRoomSig.Conn_Room_Sig parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ConnRoomSig.Conn_Room_Sig parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ConnRoomSig.Conn_Room_Sig parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ConnRoomSig.Conn_Room_Sig parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ConnRoomSig.Conn_Room_Sig parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ConnRoomSig.Conn_Room_Sig prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Conn_Room_Sig}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Conn_Room_Sig)
                ConnRoomSig.Conn_Room_SigOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return ConnRoomSig.internal_static_Conn_Room_Sig_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return ConnRoomSig.internal_static_Conn_Room_Sig_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ConnRoomSig.Conn_Room_Sig.class, ConnRoomSig.Conn_Room_Sig.Builder.class);
            }

            // Construct using ConnRoomSig.Conn_Room_Sig.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                uint32Groupcode_ = 0;

                strThirdAccount_ = "";

                uint32ConnedGroupcode_ = 0;

                strConnedThirdAccount_ = "";

                uint32CreateTime_ = 0;

                uint32ExpireTime_ = 0;

                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return ConnRoomSig.internal_static_Conn_Room_Sig_descriptor;
            }

            @java.lang.Override
            public ConnRoomSig.Conn_Room_Sig getDefaultInstanceForType() {
                return ConnRoomSig.Conn_Room_Sig.getDefaultInstance();
            }

            @java.lang.Override
            public ConnRoomSig.Conn_Room_Sig build() {
                ConnRoomSig.Conn_Room_Sig result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public ConnRoomSig.Conn_Room_Sig buildPartial() {
                ConnRoomSig.Conn_Room_Sig result = new ConnRoomSig.Conn_Room_Sig(this);
                result.uint32Groupcode_ = uint32Groupcode_;
                result.strThirdAccount_ = strThirdAccount_;
                result.uint32ConnedGroupcode_ = uint32ConnedGroupcode_;
                result.strConnedThirdAccount_ = strConnedThirdAccount_;
                result.uint32CreateTime_ = uint32CreateTime_;
                result.uint32ExpireTime_ = uint32ExpireTime_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ConnRoomSig.Conn_Room_Sig) {
                    return mergeFrom((ConnRoomSig.Conn_Room_Sig) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ConnRoomSig.Conn_Room_Sig other) {
                if (other == ConnRoomSig.Conn_Room_Sig.getDefaultInstance()) return this;
                if (other.getUint32Groupcode() != 0) {
                    setUint32Groupcode(other.getUint32Groupcode());
                }
                if (!other.getStrThirdAccount().isEmpty()) {
                    strThirdAccount_ = other.strThirdAccount_;
                    onChanged();
                }
                if (other.getUint32ConnedGroupcode() != 0) {
                    setUint32ConnedGroupcode(other.getUint32ConnedGroupcode());
                }
                if (!other.getStrConnedThirdAccount().isEmpty()) {
                    strConnedThirdAccount_ = other.strConnedThirdAccount_;
                    onChanged();
                }
                if (other.getUint32CreateTime() != 0) {
                    setUint32CreateTime(other.getUint32CreateTime());
                }
                if (other.getUint32ExpireTime() != 0) {
                    setUint32ExpireTime(other.getUint32ExpireTime());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ConnRoomSig.Conn_Room_Sig parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ConnRoomSig.Conn_Room_Sig) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int uint32Groupcode_;

            /**
             * <pre>
             * source group num
             * </pre>
             *
             * <code>uint32 uint32_groupcode = 1;</code>
             */
            public int getUint32Groupcode() {
                return uint32Groupcode_;
            }

            /**
             * <pre>
             * source group num
             * </pre>
             *
             * <code>uint32 uint32_groupcode = 1;</code>
             */
            public Builder setUint32Groupcode(int value) {

                uint32Groupcode_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * source group num
             * </pre>
             *
             * <code>uint32 uint32_groupcode = 1;</code>
             */
            public Builder clearUint32Groupcode() {

                uint32Groupcode_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object strThirdAccount_ = "";

            /**
             * <pre>
             * source account id
             * </pre>
             *
             * <code>string str_third_account = 2;</code>
             */
            public java.lang.String getStrThirdAccount() {
                java.lang.Object ref = strThirdAccount_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    strThirdAccount_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * source account id
             * </pre>
             *
             * <code>string str_third_account = 2;</code>
             */
            public com.google.protobuf.ByteString
            getStrThirdAccountBytes() {
                java.lang.Object ref = strThirdAccount_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    strThirdAccount_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * source account id
             * </pre>
             *
             * <code>string str_third_account = 2;</code>
             */
            public Builder setStrThirdAccount(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                strThirdAccount_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * source account id
             * </pre>
             *
             * <code>string str_third_account = 2;</code>
             */
            public Builder clearStrThirdAccount() {

                strThirdAccount_ = getDefaultInstance().getStrThirdAccount();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * source account id
             * </pre>
             *
             * <code>string str_third_account = 2;</code>
             */
            public Builder setStrThirdAccountBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                strThirdAccount_ = value;
                onChanged();
                return this;
            }

            private int uint32ConnedGroupcode_;

            /**
             * <pre>
             * dest group num
             * </pre>
             *
             * <code>uint32 uint32_conned_groupcode = 3;</code>
             */
            public int getUint32ConnedGroupcode() {
                return uint32ConnedGroupcode_;
            }

            /**
             * <pre>
             * dest group num
             * </pre>
             *
             * <code>uint32 uint32_conned_groupcode = 3;</code>
             */
            public Builder setUint32ConnedGroupcode(int value) {

                uint32ConnedGroupcode_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * dest group num
             * </pre>
             *
             * <code>uint32 uint32_conned_groupcode = 3;</code>
             */
            public Builder clearUint32ConnedGroupcode() {

                uint32ConnedGroupcode_ = 0;
                onChanged();
                return this;
            }

            private java.lang.Object strConnedThirdAccount_ = "";

            /**
             * <pre>
             * dest account id
             * </pre>
             *
             * <code>string str_conned_third_account = 4;</code>
             */
            public java.lang.String getStrConnedThirdAccount() {
                java.lang.Object ref = strConnedThirdAccount_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    strConnedThirdAccount_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <pre>
             * dest account id
             * </pre>
             *
             * <code>string str_conned_third_account = 4;</code>
             */
            public com.google.protobuf.ByteString
            getStrConnedThirdAccountBytes() {
                java.lang.Object ref = strConnedThirdAccount_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    strConnedThirdAccount_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <pre>
             * dest account id
             * </pre>
             *
             * <code>string str_conned_third_account = 4;</code>
             */
            public Builder setStrConnedThirdAccount(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                strConnedThirdAccount_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * dest account id
             * </pre>
             *
             * <code>string str_conned_third_account = 4;</code>
             */
            public Builder clearStrConnedThirdAccount() {

                strConnedThirdAccount_ = getDefaultInstance().getStrConnedThirdAccount();
                onChanged();
                return this;
            }

            /**
             * <pre>
             * dest account id
             * </pre>
             *
             * <code>string str_conned_third_account = 4;</code>
             */
            public Builder setStrConnedThirdAccountBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                strConnedThirdAccount_ = value;
                onChanged();
                return this;
            }

            private int uint32CreateTime_;

            /**
             * <pre>
             * create time
             * </pre>
             *
             * <code>uint32 uint32_create_time = 5;</code>
             */
            public int getUint32CreateTime() {
                return uint32CreateTime_;
            }

            /**
             * <pre>
             * create time
             * </pre>
             *
             * <code>uint32 uint32_create_time = 5;</code>
             */
            public Builder setUint32CreateTime(int value) {

                uint32CreateTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * create time
             * </pre>
             *
             * <code>uint32 uint32_create_time = 5;</code>
             */
            public Builder clearUint32CreateTime() {

                uint32CreateTime_ = 0;
                onChanged();
                return this;
            }

            private int uint32ExpireTime_;

            /**
             * <pre>
             * expire time
             * </pre>
             *
             * <code>uint32 uint32_expire_time = 6;</code>
             */
            public int getUint32ExpireTime() {
                return uint32ExpireTime_;
            }

            /**
             * <pre>
             * expire time
             * </pre>
             *
             * <code>uint32 uint32_expire_time = 6;</code>
             */
            public Builder setUint32ExpireTime(int value) {

                uint32ExpireTime_ = value;
                onChanged();
                return this;
            }

            /**
             * <pre>
             * expire time
             * </pre>
             *
             * <code>uint32 uint32_expire_time = 6;</code>
             */
            public Builder clearUint32ExpireTime() {

                uint32ExpireTime_ = 0;
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:Conn_Room_Sig)
        }

        // @@protoc_insertion_point(class_scope:Conn_Room_Sig)
        private static final ConnRoomSig.Conn_Room_Sig DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new ConnRoomSig.Conn_Room_Sig();
        }

        public static ConnRoomSig.Conn_Room_Sig getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Conn_Room_Sig>
                PARSER = new com.google.protobuf.AbstractParser<Conn_Room_Sig>() {
            @java.lang.Override
            public Conn_Room_Sig parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new Conn_Room_Sig(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<Conn_Room_Sig> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Conn_Room_Sig> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public ConnRoomSig.Conn_Room_Sig getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Conn_Room_Sig_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_Conn_Room_Sig_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\021ConnRoomSig.proto\"\277\001\n\rConn_Room_Sig\022\030\n" +
                        "\020uint32_groupcode\030\001 \001(\r\022\031\n\021str_third_acc" +
                        "ount\030\002 \001(\t\022\037\n\027uint32_conned_groupcode\030\003 " +
                        "\001(\r\022 \n\030str_conned_third_account\030\004 \001(\t\022\032\n" +
                        "\022uint32_create_time\030\005 \001(\r\022\032\n\022uint32_expi" +
                        "re_time\030\006 \001(\rB\rB\013ConnRoomSigb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_Conn_Room_Sig_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Conn_Room_Sig_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_Conn_Room_Sig_descriptor,
                new java.lang.String[]{"Uint32Groupcode", "StrThirdAccount", "Uint32ConnedGroupcode", "StrConnedThirdAccount", "Uint32CreateTime", "Uint32ExpireTime",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
